CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    login VARCHAR(50) UNIQUE NOT NULL,
    pass VARCHAR(255) NOT NULL,
    salt VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    groupid INTEGER
);
